name: .NET Builder

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build Test
      run: dotnet build KdyWeb.NetCore/KdyWeb.VideoPlay/KdyWeb.VideoPlay.csproj --no-restore
